trigger: none
pool: dockervm-agent-pool
stages:
  - stage: buildimage
    displayName: buld image 
    jobs:
    - job: 
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'acr-svc-coonection'
          repository: 'todoui'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
        