apiVersion: apps/v1
kind: Deployment
metadata:
  name: deletetask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deletetask
  template:
    metadata:
      labels:
        app: deletetask
    spec:
      containers:
      - name: deletetask
        image: devramacr1.azurecr.io/ram-repository/deletetasktodo:v1
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          value: >-
            Driver={ODBC Driver 17 for SQL Server};
            Server=tcp:devtododbsrvram1.database.windows.net,1433;
            Database=todoappdb1;
            Uid=devopsadmin;
            Pwd=P@ssw01rd@123;
            Encrypt=yes;
            TrustServerCertificate=no;
            Connection Timeout=30;